---
# EventStore

- name: EventStore | Install Repositories
  shell: curl -s https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh | sudo bash

- name: EventStore | Install
  apt: pkg=eventstore-oss={{ eventstore_version }}

- name: EventStore | Add Configuration
  template: src=../files/eventstore.conf dest=/etc/eventstore/eventstore.conf

- name: EventStore | Start
  service: name=eventstore state=started
