---
# Laravel Tools

- name: Laravel Tools | Install Laravel Installer
  shell: composer global require laravel/installer

- name: Laravel Tools | Install Lumen Installer
  shell: composer global require laravel/lumen-installer

- name: Laravel Tools | Install Envoy
  shell: composer global require laravel/envoy
